# standard jekyll configuration

permalink: /blog/:title/
pygments: true
exclude: ['Rakefile', 'README']
markdown: rdiscount

domain: barronstack.com
title: Barronstack
description: Game platform for Minecraft and others 
email: contact@barronstack.com
